name: Release Charts

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Extract Chart version
        id: extract_version
        run: |
          version="${GITHUB_REF#refs/tags/v}"
          if [ "$version" = "$GITHUB_REF" ]; then
            version="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Extracted version: $version"

      - name: Setup Helm
        uses: azure/setup-helm@v3
        # with:
        #   version: v3.14.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        # with:
        #   version: ${{ steps.extract_version.outputs.version }}
        #   # Paramètres corrects pour l'action :
        #   owner: ${{ github.repository_owner }}
        #   repo: ${{ github.event.repository.name }}
        #   # Ajoutez ceci si votre chart est dans un sous-dossier :
        #   # charts_dir: charts