name: Release Charts

on:
  push:
    tags:
      - "v*"  # Modifier ce pattern selon votre convention de tagging

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # Checkout spécifiquement le tag

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Extract Chart version
        id: extract_version
        run: |
          # Supprime le préfixe 'v' si présent (v1.0.0 → 1.0.0)
          version="${GITHUB_REF#refs/tags/v}"
          # Si le tag ne commence pas par 'v', prendre toute la partie après 'tags/'
          if [ "$version" = "$GITHUB_REF" ]; then
            version="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: ${{ steps.extract_version.outputs.version }}  # Spécifie la version du chart